/*
 * This source file was generated by the Gradle 'init' task
 */
package org.andreip;

import java.io.*;
import static org.andreip.scenes.SceneFactory.*;

public class App {
    public static void main(String[] args) {
        var camera = getChapter1Scene();
        
        try {
            camera.render();
        } catch (IOException e) {
            e.printStackTrace();
        }
    }
}

